# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  N = 1 # max number of worker nodes

  #=============#
  # Master Node #
  #=============#

    config.vm.define "kubernetes-master-node" do |cfg|
      cfg.vm.box = "ubuntu/jammy64"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "kubernetes-master-node"
        vb.cpus = 2
        vb.memory = 2560
        vb.customize ["modifyvm", :id, "--groups", "/group-of-kubernetes"]
      end
      cfg.vm.host_name = "kubernetes-master-node"
      cfg.vm.network "private_network", ip: "192.168.56.100"
      cfg.vm.network "forwarded_port", guest: 22, host: 60010, auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "config.sh", args: N
      cfg.vm.provision "shell", path: "install_pkg.sh"
      cfg.vm.provision "shell", path: "master_node.sh", args: N
    end

  #==============#
  # Worker Nodes #
  #==============#

  (1..N).each do |i|
    config.vm.define "kubernetes-worker-node-#{i}" do |cfg|
      cfg.vm.box = "ubuntu/jammy64"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "kubernetes-worker-node-#{i}"
        vb.cpus = 2
        vb.memory = 2560
        vb.customize ["modifyvm", :id, "--groups", "/group-of-kubernetes"]
      end
      cfg.vm.host_name = "kubernetes-worker-node-#{i}"
      cfg.vm.network "private_network", ip: "192.168.56.10#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "config.sh", args: N
      cfg.vm.provision "shell", path: "install_pkg.sh"
      cfg.vm.provision "shell", path: "work_nodes.sh"
    end
  end
end