# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  N = 2 # max number of nodes

  #==================#
  # Kubernetes Nodes #
  #==================#

  (1..N).each do |i|
    config.vm.define "Node-#{i}" do |cfg|
      cfg.vm.box = "ubuntu/jammy64"
      cfg.vm.provider "virtualbox" do |vb|
        vb.name = "Node-#{i}"
        vb.cpus = 1
        vb.memory = 1024
        vb.customize ["modifyvm", :id, "--groups", "/Group-of-Node"]
      end
      cfg.vm.host_name = "Node-#{i}"
      cfg.vm.network "public_network", ip: "192.168.1.1#{i}", bridge: "outsidebr0"
      cfg.vm.network "public_network", ip: "10.21.87.1#{i}", bridge: "insidebr0"
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
      cfg.vm.provision "shell", path: "config.sh", args: N
      cfg.vm.provision "shell", path: "install-pkg.sh"
      cfg.vm.provision "shell", path: "join-node.sh"
    end
  end
end