# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  N = 1 # max number of worker nodes

  #==============#
  # Worker Nodes #
  #==============#

  (1..N).each do |i|
    config.vm.define "k8s-node-#{i}" do |cfg|
      cfg.vm.box = "generic/ubuntu2204"
      cfg.vm.provider :libvirt do |libvirt|
        libvirt.driver = 'kvm'
        libvirt.host = "libvirt-server"
        libvirt.uri = 'qemu:///system'
        libvirt.cpus = 2
        libvirt.memory = 2048
      end
      cfg.vm.host_name = "kubernetes-worker-node-#{i}"
      cfg.vm.network "private_network", ip: "10.253.26.10#{i}"
      cfg.vm.network "forwarded_port", guest: 22, host: "6010#{i}", auto_correct: true, id: "ssh"
      cfg.vm.synced_folder "../data", "/vagrant", disabled: true
#       cfg.vm.provision "shell", path: "config.sh", args: N
#       cfg.vm.provision "shell", path: "install_pkg.sh"
#       cfg.vm.provision "shell", path: "work_nodes.sh"
    end
  end
end
